import catImage from "../../../assets/cat.jpeg";

export const DUMMY_DATA = [
  {
    id: 1,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 2,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 3,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 4,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 5,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 6,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 7,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 8,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 9,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 10,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 11,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 12,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 13,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 14,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 15,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 16,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 17,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 18,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 19,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 20,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 21,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 22,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 23,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
  {
    id: 24,
    url: catImage,
    title: "Best cat ever",
    user: "franco cragnolini",
  },
];
